# Generated by Django 3.0.5 on 2020-05-05 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('youtube_link', models.TextField(verbose_name='youtube link')),
                ('date', models.DateField(verbose_name='date published')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_spot.Artist')),
            ],
        ),
    ]
