# Generated by Django 3.0.5 on 2020-05-06 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_spot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist_id',
            new_name='artist',
        ),
    ]
