# Generated by Django 3.0.5 on 2020-05-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_spot', '0002_auto_20200506_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='youtube_embedded_link',
            field=models.TextField(blank=True, verbose_name='embedded link'),
        ),
    ]
