# Generated by Django 3.0.5 on 2020-05-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_spot', '0003_song_youtube_embedded_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date',
            field=models.DateField(blank=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='song',
            name='youtube_link',
            field=models.TextField(blank=True, verbose_name='youtube link'),
        ),
    ]
