# Generated by Django 3.0.6 on 2020-05-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_spot', '0004_auto_20200506_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='song',
            name='youtube_embedded_link',
            field=models.TextField(blank=True, null=True, verbose_name='embedded link'),
        ),
        migrations.AlterField(
            model_name='song',
            name='youtube_link',
            field=models.TextField(blank=True, null=True, verbose_name='youtube link'),
        ),
    ]
